Documents/symfony/mapsiv3-dev/src/Entity/Audit.php
<?php

namespace App\Entity;

use App\Repository\AuditRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass=AuditRepository::class)
 */
class Audit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $designation;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $CreatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $PublishedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $ClosedAt;

    /**
     * @ORM\ManyToOne(targetEntity=People::class, inversedBy="auditsresponsable")
     */
    private $responsable;

    /**
     * @ORM\ManyToOne(targetEntity=People::class, inversedBy="auditssuppleant")
     */
    private $suppleant;

    /**
     * @ORM\ManyToMany(targetEntity=People::class, inversedBy="auditspeoples")
     */
    private $Peoples;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $resultat;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $commentaire;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resultatlight;

    /**
     * @ORM\ManyToMany(targetEntity=TypeConformite::class, inversedBy="auditstypeconformite")
     */
    private $typeconformite;

    /**
     * @ORM\ManyToMany(targetEntity=Processus::class, inversedBy="auditsprocessus")
     */
    private $processuses;

    /**
     * @ORM\ManyToMany(targetEntity=Site::class, inversedBy="auditssite")
     */
    private $sites;

    /**
     * @ORM\ManyToMany(targetEntity=Tier::class, inversedBy="auditstier")
     */
    private $tiers;

    /**
     * @ORM\ManyToMany(targetEntity=Flux::class, inversedBy="auditsflux")
     */
    private $traitements;

    /**
     * @ORM\ManyToMany(targetEntity=Action::class, inversedBy="auditsaction")
     */
    private $actions;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $statut;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $ValidatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=People::class, inversedBy="auditsvalidator")
     */
    private $validator;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $validationstatut;

    /**
     * @ORM\Column(type="string", length=255)
     * 
     * @Gedmo\Slug(fields={"designation"})
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity=MapsiCustomer::class, inversedBy="auditscustomer")
     */
    private $customer;

    /**
     * @ORM\ManyToOne(targetEntity=People::class, inversedBy="auditspublisher")
     */
    private $publisher;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $PreparedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $StartedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $FinishedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $ReportedAt;

    /**
     * @ORM\ManyToOne(targetEntity=TypeAudit::class, inversedBy="audits")
     */
    private $typeaudit;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $progres;

    /**
     * @ORM\OneToMany(targetEntity=NonConformite::class, mappedBy="audit", orphanRemoval=true, cascade={"persist"})
     */
    private $nonconformites;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $auditeur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $organisme;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;


    public function __construct()
    {
        $this->Peoples = new ArrayCollection();
        $this->typeconformite = new ArrayCollection();
        $this->processuses = new ArrayCollection();
        $this->sites = new ArrayCollection();
        $this->tiers = new ArrayCollection();
        $this->traitements = new ArrayCollection();
        $this->actions = new ArrayCollection();
        $this->nonconformites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(string $designation): self
    {
        $this->designation = $designation;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(?\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->PublishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $PublishedAt): self
    {
        $this->PublishedAt = $PublishedAt;

        return $this;
    }

    public function getClosedAt(): ?\DateTimeInterface
    {
        return $this->ClosedAt;
    }

    public function setClosedAt(?\DateTimeInterface $ClosedAt): self
    {
        $this->ClosedAt = $ClosedAt;

        return $this;
    }

    public function getResponsable(): ?People
    {
        return $this->responsable;
    }

    public function setResponsable(?People $responsable): self
    {
        $this->responsable = $responsable;

        return $this;
    }

    public function getSuppleant(): ?People
    {
        return $this->suppleant;
    }

    public function setSuppleant(?People $suppleant): self
    {
        $this->suppleant = $suppleant;

        return $this;
    }

    /**
     * @return Collection|People[]
     */
    public function getPeoples(): Collection
    {
        return $this->Peoples;
    }

    public function addPeople(People $people): self
    {
        if (!$this->Peoples->contains($people)) {
            $this->Peoples[] = $people;
        }

        return $this;
    }

    public function removePeople(People $people): self
    {
        $this->Peoples->removeElement($people);

        return $this;
    }

    public function getResultat(): ?string
    {
        return $this->resultat;
    }

    public function setResultat(?string $resultat): self
    {
        $this->resultat = $resultat;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getResultatlight(): ?string
    {
        return $this->resultatlight;
    }

    public function setResultatlight(?string $resultatlight): self
    {
        $this->resultatlight = $resultatlight;

        return $this;
    }

    /**
     * @return Collection|TypeConformite[]
     */
    public function getTypeconformite(): Collection
    {
        return $this->typeconformite;
    }

    public function addTypeconformite(TypeConformite $typeconformite): self
    {
        if (!$this->typeconformite->contains($typeconformite)) {
            $this->typeconformite[] = $typeconformite;
        }

        return $this;
    }

    public function removeTypeconformite(TypeConformite $typeconformite): self
    {
        $this->typeconformite->removeElement($typeconformite);

        return $this;
    }

    /**
     * @return Collection|Processus[]
     */
    public function getProcessuses(): Collection
    {
        return $this->processuses;
    }

    public function addProcessus(Processus $processus): self
    {
        if (!$this->processuses->contains($processus)) {
            $this->processuses[] = $processus;
        }

        return $this;
    }

    public function removeProcessus(Processus $processus): self
    {
        $this->processuses->removeElement($processus);

        return $this;
    }

    /**
     * @return Collection|Site[]
     */
    public function getSites(): Collection
    {
        return $this->sites;
    }

    public function addSite(Site $site): self
    {
        if (!$this->sites->contains($site)) {
            $this->sites[] = $site;
        }

        return $this;
    }

    public function removeSite(Site $site): self
    {
        $this->sites->removeElement($site);

        return $this;
    }

    /**
     * @return Collection|Tier[]
     */
    public function getTiers(): Collection
    {
        return $this->tiers;
    }

    public function addTier(Tier $tier): self
    {
        if (!$this->tiers->contains($tier)) {
            $this->tiers[] = $tier;
        }

        return $this;
    }

    public function removeTier(Tier $tier): self
    {
        $this->tiers->removeElement($tier);

        return $this;
    }

    /**
     * @return Collection|Flux[]
     */
    public function getTraitements(): Collection
    {
        return $this->traitements;
    }

    public function addTraitement(Flux $traitement): self
    {
        if (!$this->traitements->contains($traitement)) {
            $this->traitements[] = $traitement;
        }

        return $this;
    }

    public function removeTraitement(Flux $traitement): self
    {
        $this->traitements->removeElement($traitement);

        return $this;
    }

    /**
     * @return Collection|Action[]
     */

Documents/symfony/mapsiv3-dev/templates/datatable/actionminitable.html.twig
<table class="compact table table-bordered dataTables-miniaction" >
    <thead>
        <tr>
            <th scope="col">Désignation</th>
            <th scope="col">Progression</th>
            <th scope="col">Jalon</th>
            <th scope="col">Manager</th>
        </tr>
    </thead>
    <tbody>
        {% for action in actions if action.progression != 100 %}
        <tr>
            <td class="table-title" scope="row">
                <span class="badge badge-secondary small">AC-{{ action.id }}</span> <a class="" href="{{path('action_edit',{'slug' : action.slug, 'id' : action.id, 'r' : r, 'rr' : rr} ) }}">{{ action.designation }}</a></td>
            <td scope="row" class="project-completion" data-order="{{ action.progression }}">
                <small>Progression : {{ action.progression | round | default("0")  }}%</small>
                    <div class="progress progress-mini">
                        <div style="width: {{ action.progression | round | default("0")  }}%;" class="progress-bar"></div>
                    </div>
            </td>
            <td scope="row" data-order="{{ action.jalonConnectActions | length  }}">
                <a  tabindex="0"
                    role="button" 
                    id="jalon{{ action.id }}"
                    data-container="body" 
                    data-toggle="popover"
                    data-placement="bottom" 
                    data-html="true"
                    data-trigger="focus"
                    data-title="{{ action.designation }}" 
                    data-content="
                        {% for jalon in action.jalonConnectActions %}
                            <span class='small'><b>{% if jalon.fini ==1 %} <i class='fa fa-check'></i>{% endif %} {{ jalon.date | date('M Y')  }}</b> {{ jalon.jalon | default('N/C')  }}</span><br>								
            {% endfor %}">
                    {{ action.jalonConnectActions | length  }} tâche{% if action.jalonConnectActions | length > 1 %}s{% endif %}
                </a>
            </td>
                
            <td scope="row"><b>{{ action.responsable.firstname | default("N/C")  }} {{ action.responsable.lastname | default("")  }}</b>																							    </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

Documents/symfony/mapsiv3-dev/templates/datatable/actiontable.html.twig
<div class="row">
	<div class="col-lg-12">
        <form class="form-inline" role="form">
        <div id="buttondt-action" style="margin-right:8px">
        </div>
        <button type="button" class="btn btn-default m-r-sm">
        Qté <span class="badge badge-light rowcounttot-action"></span>
        <span class="sr-only">Toutes les entrées de la base pour cette entité</span>
        </button>
        <button type="button" class="btn btn-default m-r-sm">
        Visible <span class="badge badge-light rowcountview-action"></span>
        <span class="sr-only">Identifie le nombre de lignes visibles</span>
        </button>
        <button type="button" class="btn btn-default m-r-sm">
        Sélect. <span class="badge badge-light rowcountselect-action">0</span>
        <span class="sr-only">Identifie le nombre de ligne sélectionnées</span>
        </button>
        <div class="input-group">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-addon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                        </svg>
                    </span>
                </div>
                <input type="text" id="searchdt-action" name="searchdt" class="form-control">
            </div>
        </div>
        </form>
    </div>
</div>

<table class="hover table table-bordered  dataTables-action" >
    <thead>
    <tr>
        <th scope="col" class="export pdf" style="width:80px">Etat</th>
        <th scope="col">Désignation</th>
        <th scope="col">Managers</th>
        <th scope="col">Progression</th>
        <th scope="col export">Statut</th>
        <th scope="col" class="export">Budget</th>
        <th scope="col">Tâches</th>
        <th scope="col" class="export pdf">Fin revue</th>
        <th scope="col" class="no-show export pdf">Fin revue</th>
        <th scope="col" class="no-sort" style="width:60px"></th>
        <th scope="col" class="no-show export pdf">Désignation</th>
        <th scope="col" class="no-show export pdf">Progression</th>
        <th scope="col" class="no-show export pdf">Responsable</th>
        <th scope="col" class="no-show export">Suppleant</th>
        <th scope="col" class="no-show export">Nb jalons</th>
        <th scope="col" class="no-show export">Jalons</th>
        <th scope="col" class="no-show export">Budget</th>
        <th scope="col" class="no-show export">J/H</th>
        <th scope="col" class="no-show export"></th>
    </tr>
    </thead>
    <tbody>
        {% set sumbudgettot = 0 %}
        {% set sumetptot = 0 %}
    {% for action in actions | sortbyfield('datefin') %}
            <tr>
                <td class="text-center">
                    <span class="badge">
                        {% for place in workflow_marked_places(action) %}
                            <strong>{{ workflow_metadata(action, 'title', place) ?: ''}}</strong>
                        {% endfor %}
                    </span>
                </td>
                <td class="table-title" scope="row">
                    <a class="" href="{{path('action_edit',{'slug' : action.slug, 'id' : action.id, 'r' : r, 'rr' : rr} ) }}">{{ action.designation }}</a> 
                    <span class="badge badge-secondary small">AC-{{ action.id }}</span><br>
                    <small>PROJ{{ action.projet.id | default("N/C")  }}-{{ action.projet.designation | default("N/C")  }}</small>
                </td>
                <td scope="row"><b>{{ action.responsable.firstname | default("N/C")  }} {{ action.responsable.lastname | default("")  }}</b><br>
                    {{ action.suppleant.firstname | default("N/C")  }} {{ action.suppleant.lastname | default("")  }}
                </td>
                <td scope="row" class="project-completion" data-order="{{ action.progression }}">
                    <small>Progression : {{ action.progression | round | default("0")  }}%</small>
                        <div class="progress progress-mini">
                            <div style="width: {{ action.progression | round | default("0")  }}%;" class="progress-bar"></div>
                        </div>
                </td>
                <td scope="row">
                    {% set statutaction = "" %}
                    {% set statutclass = "" %}
                    {% for jalon in action.jalonConnectActions %}
                        {% if jalon.progression==100 %}
                        {% set statutaction = "Terminé" %}
                        {% set statutclass = "badge badge-success small" %}
                        {% elseif jalon.progression == 0 and jalon.responsable is null %}
                        {% set statutclass = "badge small" %}
                        {% set statutaction = "Non démarré" %}
                        {% elseif jalon.progression < 100 and jalon.daterevue > jalon.date %}
                        {% set difference = date(jalon.daterevue).diff(date(jalon.date)) %}
                        {% set leftDays = difference.days %}
                        {% set statutclass = "badge badge-warning small" %}
                        {% set statutaction = "En cours !" %}
                        {% else %}
                        {% set statutclass = "badge badge-primary small" %}
                        {% set statutaction = "En cours" %}
                        {% endif %}
                    {% endfor %}
                    <span class="{{ statutclass }}">
                        {{ statutaction}}
                    </span>
                </td>
                <td scope="row"> 
                    {% set budget = 0 %}
                    {% for b in action.jalonConnectActions %}
                        {% set budget = budget + b.budget %}
                    {% endfor %}
                    {{ budget | number_format(0, '.', ' ') | default("") }} €
                </td>
                <td scope="row" data-order="{{ action.jalonConnectActions | length  }}">
                    <a  tabindex="0"
                        role="button" 
                        id="jalon{{ action.id }}"
                        data-container="body" 
                        data-toggle="popover"
                        data-placement="bottom" 
                        data-html="true"
                        data-trigger="focus"
                        data-title="" 
                        data-content="
                            <ul class='list-group'>
                            {% for jalon in action.jalonConnectActions %}
                                <li class='list-group-item list-group-item-primary'><span class='small'><a  class='text-secondary' href='{{path('tache_edit',{'id' : jalon.id, 'r' : app.request.get('_route'), 'rr' : conformite })}}'> 
                                {{ jalon.date | date('M Y')  }} > {{ jalon.jalon | default('')  }}</a> {% if jalon.fini ==1 %} <i class='fa fa-check'></i>{% endif %}</span></li>							
                            {% endfor %}
                            </ul">
                        <span class="badge"><strong>{{ action.jalonConnectActions | length  }}</strong></span>
                    </a>
                </td>
                <td>
                    {{ action.datefinrevue | date("d M Y") }}
                    {% set difference = date(action.datefinrevue ).diff(date(action.datefin)) %}
                    {% set delayDays = difference.days %}
                    {% if delayDays > 0 %}<br><small><strong>({{ delayDays }} jours de retard)</strong></small>{% endif %}
                </td>
                <td>
                    {{ action.datefinrevue | date("d M Y") }}
                </td>
                
                <td data-order="{{ action.PublishedAt | date("Ymd")}}" class="text-center">
                    <button id="btnGroupDrop1" type="button" class="btn btn-outline-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-info"></i>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                        <a class="dropdown-item" href="{{path('action_edit',{'slug' : action.slug, 'id' : action.id, 'r' : r, 'rr' : rr} ) }}"> Afficher</a>
                        {% if is_granted('ROLE_ADMIN')  or is_granted('ROLE_USER_ALLOWDELETE') %}
                        <a class="dropdown-item del" href="{{path('action_remove',{'slug' : action.slug, 'id' : action.id, 'r' : r, 'rr' : rr} ) }}"> Supprimer</a>
                        {% endif %}
                        <a class="dropdown-item">
                            <small>Modifiée le {{ action.PublishedAt | date("d M Y")}}</small>
                            <small> {% set today = "now"|date("Y/m/d") %}
                            {% set difference = date(action.PublishedAt).diff(date(today)) %}
                            {% set leftDays = difference.days %}
                            {% if leftDays >= 180 and leftDays < 360 %}
                            <small class="text-warning">({{ leftDays }}j)</small>
                            {% elseif leftDays >= 360 %}
                                <small class="text-danger">({{ leftDays }}j)</small>
                            {% else %}
                                <small>({{ leftDays }}j)</small>
                            {% endif %}
                            <br>par {{action.publisher.firstname | default("") }} {{ action.publisher.lastname | default("") }}</small>
                        </a>
                    </div>
                </td>
                <td>{{ action.designation | default("N/C")  }}</td>                
                <td>{{ action.progression | round | default("0")  }}%</td>
                <td>{{ action.responsable.firstname | default("")  }} {{ action.responsable.lastname | default("")  }}</td>
                <td>{{ action.suppleant.firstname | default("")  }} {{ action.suppleant.lastname | default("")  }}</td>
                <td>{{ action.jalonConnectActions | length  }}</td>
                
                <td>{% for jalon in action.jalonConnectActions %}
                        {{ jalon.date | date('M Y')  }} {{ jalon.jalon | default('')  }}<br>								
                    {% endfor %}
                </td>
                <td>
                    {% set sumbudget = 0 %}
                        {% set sumbudgettot = action.budget + sumbudget %}							
                        {{ sumbudgettot }}
                </td>
                <td>{% set sumetp = 0 %}
                        {% set sumetptot = action.etp + sumetp %}							
                        {{ sumetptot }}
                </td>
                <td>{{ action.publishedat | date("d/m/Y")  }}</td>
            </tr>
    {% endfor %}
    </tbody>
</table>

Documents/symfony/mapsiv3-dev/templates/datatable/fluxtablev2.html.twig
{{ include('datatable/tableheader.html.twig', {dtname : 'flux' }) }}

<table id="dataTables-flux" class="table table-bordered select table-hover">
    <thead>
        <tr>
            <th class="align-middle"></th>
            <th>Désignation</th>
            <th>Responsable</th>
            <th>Processus</th>
            <th>Relations</th>
            <th>Comply</th>
            <th>Statut</th>
        </tr>
    </thead>
</table>

Documents/symfony/mapsiv3-dev/templates/datatable/metiertable.html.twig
<table class="hover table table-bordered dataTables-metier" >
    <thead>
        <tr>
            <th scope="col">Désignation</th>
            <th scope="col">Managers</th>
            <th scope="col">Collaborateurs</th>
            <th scope="col" class="no-sort"></th>
        </tr>
    </thead>
    <tbody>
        {% for metier in metiers %}
            <article>
                <tr>
                    <td  class="table-title"  scope="row" data-order="{{ metier.designation }}">
                        <a class="" href="{{path('metier_edit',{'id' : metier.id,'r' : 'metier'} ) }}">{{ metier.code | default("") }} {{ metier.designation }}</a> 
                    <span class="badge badge-secondary small">MET-{{ metier.id }}</span>
                    </td>
                    <td scope="row"><b>{{ metier.directeur.firstname | default("")  }} {{ metier.directeur.lastname | default("")  }}</b><br>
                    {{ metier.suppleant.firstname | default("")  }} {{ metier.suppleant.lastname | default("")  }}
                    </td>
                    <td><span class="badge badge-primary">{{ metier.peoples|length }}</span></td>
                    <td data-order="{{ metier.PublishedAt | date("Ymd")}}">
                        <button id="btnGroupDrop1" type="button" class="btn btn-outline-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-info"></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                        <a class="dropdown-item" href="{{path('metier_edit',{'slug' : metier.slug, 'id' : metier.id, 'r' : r, 'rr' : rr} ) }}"> Afficher</a>
                        {% if is_granted('ROLE_ADMIN')  or is_granted('ROLE_USER_ALLOWDELETE') %}
                        <a class="dropdown-item del" href="{{path('metier_remove',{'slug' : metier.slug, 'id' : metier.id, 'r' : r, 'rr' : rr} ) }}"> Supprimer</a>
                        {% endif %}
                            <a class="dropdown-item">
                                <small>Modifiée le {{ metier.PublishedAt | date("d M Y")}}</small>
                                <small> {% set today = "now"|date("Y/m/d") %}
                                {% set difference = date(metier.PublishedAt).diff(date(today)) %}
                                {% set leftDays = difference.days %}
                                {% if leftDays >= 180 and leftDays < 360 %}
                                <small class="text-warning">({{ leftDays }}j)</small>
                                {% elseif leftDays >= 360 %}
                                    <small class="text-danger">({{ leftDays }}j)</small>
                                {% else %}
                                    <small>({{ leftDays }}j)</small>
                                {% endif %}
                                <br>par {{metier.publisher.firstname | default("") }} {{ metier.publisher.lastname | default("") }}</small>
                            </a>
                        </div>
                    </td>
                </tr>
            </article>
        {% endfor %}
    </tbody>
</table>

Documents/symfony/mapsiv3-dev/templates/datatable/objetmetiertablev2.html.twig
{{ include('datatable/tableheader.html.twig', {dtname : 'objet_metier' }) }}

<table id="dataTables-objet_metier" class="table table-bordered select table-hover">
    <thead>
        <tr>
            <th class="align-middle"></th>
            <th>Désignation</th>
            <th>Responsable</th>
            <th>Processus</th>
            <th>Relations</th>
            <th>Comply</th>
            <th>Statut</th>
        </tr>
    </thead>
</table>

Documents/symfony/mapsiv3-dev/templates/datatable/sitetable.html.twig
<table class="hover table table-bordered dataTables-site" >
    <thead>
        <tr>
            <th scope="col">Désignation</th>
            <th scope="col">Type de site</th>
            <th scope="col">Ville</th>
            <th scope="col">Managers</th>
            <th scope="col">Positions</th>
            <th scope="col" class="no-sort"></th>
        </tr>
    </thead>
    <tbody>
        {% for site in sites %}
            <article>
                <tr>
                        <td  class="table-title"  scope="row" data-order="{{ site.designation }}">
                    <a class="" href="{{path('site_edit',{'id' : site.id} ) }}">{{ site.designation | title }}</a>
                    <span class="badge badge-secondary small">SIT-{{ site.id }}</span>
                    </td>
                    <td scope="row">{{ site.typedesite.designation | default("")  }}</td>
                    <td scope="row">{{ site.ville | default("")  }}</td>
                    <td scope="row"><b>{{ site.responsable.firstname | default("")  }} {{ site.responsable.lastname | default("")  }}</b><br>
                    {{ site.suppleant.firstname | default("")  }} {{ site.suppleant.lastname | default("")  }}
                    </td>
                    <td><span class="badge badge-primary">{{ site.peoples|length }}</span></td>
                    
                    <td data-order="{{ site.PublishedAt | date("Ymd")}}">
                        <button id="btnGroupDrop1" type="button" class="btn btn-outline-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-info"></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                            <a class="dropdown-item" href="{{path('site_edit',{'slug' : site.slug, 'id' : site.id, 'r' : r, 'rr' : rr} ) }}"> Afficher</a>
                            {% if is_granted('ROLE_ADMIN')  or is_granted('ROLE_USER_ALLOWDELETE') %}
                            <a class="dropdown-item del" href="{{path('site_remove',{'slug' : site.slug, 'id' : site.id, 'r' : r, 'rr' : rr} ) }}"> Supprimer</a>
                            {% endif %}
                            <a class="dropdown-item">
                                <small>Modifiée le {{ site.PublishedAt | date("d M Y")}}</small>
                                <small> {% set today = "now"|date("Y/m/d") %}
                                {% set difference = date(site.PublishedAt).diff(date(today)) %}
                                {% set leftDays = difference.days %}
                                {% if leftDays >= 180 and leftDays < 360 %}
                                <small class="text-warning">({{ leftDays }}j)</small>
                                {% elseif leftDays >= 360 %}
                                    <small class="text-danger">({{ leftDays }}j)</small>
                                {% else %}
                                    <small>({{ leftDays }}j)</small>
                                {% endif %}
                                <br>par {{site.publisher.firstname | default("") }} {{ site.publisher.lastname | default("") }}</small>
                            </a>
                        </div>
                    </td>
                </tr>
            </article>
        {% endfor %}
    </tbody>
</table>